### ISSUE TITLE
As an outsider, I'd like to be able to learn how grants in my community have affected notable trends in a dynamic, relevant way (not just every 2 years)

### ISSUE THREAD

**Issue by timsjpark** [CodeForBoulder/trends-online#18]

**Comment by timsjpark** [comment]
CF Insiders think a bulletin board might be a good option. Other options might include a blog/news articles.

**Comment by ZachLamb** [comment]
Added to rough personas here: https://docs.google.com/spreadsheets/d/1u41HzCrC7pK1aYCj3sZ_4hEcpgmdJ-qCAXd_RgmWYP0/edit#gid=0
